#!/usr/bin/env bash
set -eo pipefail
[[ "${DEBUG}" == "true" ]] && set -x

if [[ -z "${OWNCLOUD_ENTRYPOINT_INITIALIZED}" ]]; then
  for FILE in $(find /etc/entrypoint.d -iname "*.sh" | sort); do
    # shellcheck disable=SC1090,SC2086
    source ${FILE}
  done
fi

case ${1} in
install)
  COMMAND="occ maintenance:install --no-interaction --data-dir ${OWNCLOUD_VOLUME_FILES}"
  [[ -n "${OWNCLOUD_DB_TYPE}" ]] && COMMAND="${COMMAND} --database ${OWNCLOUD_DB_TYPE}"
  [[ -n "${OWNCLOUD_DB_NAME}" ]] && COMMAND="${COMMAND} --database-name ${OWNCLOUD_DB_NAME}"
  [[ -n "${OWNCLOUD_DB_USERNAME}" ]] && COMMAND="${COMMAND} --database-user ${OWNCLOUD_DB_USERNAME}"
  [[ -n "${OWNCLOUD_DB_PASSWORD}" ]] && COMMAND="${COMMAND} --database-pass ${OWNCLOUD_DB_PASSWORD}"
  [[ -n "${OWNCLOUD_DB_HOST}" ]] && COMMAND="${COMMAND} --database-host ${OWNCLOUD_DB_HOST}"
  [[ -n "${OWNCLOUD_DB_PREFIX}" ]] && COMMAND="${COMMAND} --database-table-prefix ${OWNCLOUD_DB_PREFIX}"
  [[ -n "${OWNCLOUD_ADMIN_USERNAME}" ]] && COMMAND="${COMMAND} --admin-user ${OWNCLOUD_ADMIN_USERNAME}"
  [[ -n "${OWNCLOUD_ADMIN_PASSWORD}" ]] && COMMAND="${COMMAND} --admin-pass ${OWNCLOUD_ADMIN_PASSWORD}"

  set +e
  ${COMMAND}
  RES=$?
  

  if [[ "${RES}" -ge "1" ]]; then
    exit ${RES}
  else

  # FOR the meme
  # Evrything should be installed and should be okay to fail 
  # We temporarly allow root to have read and write permission to ensure that we
  # read and write to config.php
  # UNSAFE {
      set +eo pipefail
      # TEMPORARY Permission hack 
      chown root:root config/config.php
      /var/www/owncloud/occ app:enable files_external
      /var/www/owncloud/occ config:app:set core enable_external_storage --value=yes
      chown -R www-data:www-data ${SHARE:-/shared/}
      chmod -R 750 /mnt/data
      # Create shared directory at /shared/ by default if not set
      /var/www/owncloud/occ files_external:create -c "datadir=${SHARE_LOCATION:-./tmp}/Public" /share/ local null::null 
      /var/www/owncloud/occ files:scan --all 
      chown www-data:www-data config/config.php
      set -eo pipefail
      exit 0
    # }
  fi
  ;;
migrate)
  COMMAND="occ upgrade --no-interaction"

  set +e
  ${COMMAND}
  RES=$?
  set -e

  if [[ "${RES}" -ge "4" ]]; then
    exit ${RES}
  else
    exit 0
  fi
  ;;
installed)
  if [[ $(occ -V | awk -F- '$1=="ownCloud is not installed "{print "false"}') == "false" ]]; then
    exit 1
  else
    exit 0
  fi
  ;;
*)
  for FILE in $(find /etc/owncloud.d -iname "*.sh" | sort); do
    # shellcheck disable=SC1090,SC2086
    source ${FILE}
  done

  exec "$@"
  ;;
esac
